from __future__ import annotations

import argparse
import json
from pathlib import Path


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def metric(data: dict, key: str) -> float:
    return float(data["manual_crosscheck"][key])


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate LaTeX result macros from verified simulation JSON.")
    parser.add_argument("--project", type=Path, default=Path(__file__).resolve().parent.parent)
    args = parser.parse_args()
    project = args.project.resolve()

    baseline = load(
        project
        / "results"
        / "full_adc_latest_bypass_890m_norm_nf100k_matched_cx"
        / "analysis"
        / "metrics.json"
    )
    calibrated = load(
        project
        / "results"
        / "full_adc_latest_frame_cal_890m_norm_nf100k_matched_cx"
        / "analysis"
        / "metrics.json"
    )
    calibration = load(
        project
        / "results"
        / "full_adc_latest_frame_cal_890m_norm_nf100k_matched_cx"
        / "calibration_summary.json"
    )
    if not calibration.get("complete"):
        raise RuntimeError("Calibration summary is not complete (requires DONE=1, ERR=0, six targets and final weights).")

    weights = calibration["weights"]["values_lsb"]
    physical = [2053.805632, 1027.820352, 513.12256, 256.0, 256.0, 128.0]
    physical_radix = [
        physical[0] - sum(physical[1:5]),
        physical[1] - sum(physical[2:5]),
        physical[2] - sum(physical[3:5]),
    ]
    decoded_radix = [
        weights[0] - sum(weights[1:5]),
        weights[1] - sum(weights[2:5]),
        weights[2] - sum(weights[3:5]),
    ]
    finish = calibration["finish"]
    baseline_sndr = metric(baseline, "sndr_dbc")
    baseline_sfdr = metric(baseline, "sfdr_dbc")
    calibrated_sndr = metric(calibrated, "sndr_dbc")
    calibrated_sfdr = metric(calibrated, "sfdr_dbc")
    baseline_thd = metric(baseline, "thd_dbc")
    calibrated_thd = metric(calibrated, "thd_dbc")
    lines = [
        "% Generated by scripts/update_report_macros.py; do not edit numeric values manually.",
        f"\\newcommand{{\\BaselineSNDR}}{{{baseline_sndr:.2f} dB}}",
        f"\\newcommand{{\\BaselineSFDR}}{{{baseline_sfdr:.2f} dB}}",
        f"\\newcommand{{\\BaselineENOB}}{{{metric(baseline, 'enob'):.3f} bit}}",
        f"\\newcommand{{\\BaselineSNR}}{{{metric(baseline, 'snr_dbc'):.2f} dB}}",
        f"\\newcommand{{\\BaselineTHD}}{{{baseline_thd:.2f} dBc}}",
        f"\\newcommand{{\\CalibratedSNDR}}{{{calibrated_sndr:.2f} dB}}",
        f"\\newcommand{{\\CalibratedSFDR}}{{{calibrated_sfdr:.2f} dB}}",
        f"\\newcommand{{\\CalibratedENOB}}{{{metric(calibrated, 'enob'):.3f} bit}}",
        f"\\newcommand{{\\CalibratedSNR}}{{{metric(calibrated, 'snr_dbc'):.2f} dB}}",
        f"\\newcommand{{\\CalibratedTHD}}{{{calibrated_thd:.2f} dBc}}",
        f"\\newcommand{{\\SNDRGain}}{{{calibrated_sndr - baseline_sndr:+.2f} dB}}",
        f"\\newcommand{{\\SFDRGain}}{{{calibrated_sfdr - baseline_sfdr:+.2f} dB}}",
        f"\\newcommand{{\\THDReduction}}{{{baseline_thd - calibrated_thd:+.2f} dB}}",
        f"\\newcommand{{\\BaselineCodeRange}}{{{baseline['code_min']}--{baseline['code_max']}}}",
        f"\\newcommand{{\\CalibratedCodeRange}}{{{calibrated['code_min']}--{calibrated['code_max']}}}",
        f"\\newcommand{{\\CtwelveResidual}}{{{weights[0] - physical[0]:+.4f} LSB}}",
        f"\\newcommand{{\\CelevenResidual}}{{{weights[1] - physical[1]:+.4f} LSB}}",
        f"\\newcommand{{\\CtenResidual}}{{{weights[2] - physical[2]:+.4f} LSB}}",
        f"\\newcommand{{\\CtwelveRadixError}}{{{decoded_radix[0] - physical_radix[0]:+.4f} LSB}}",
        f"\\newcommand{{\\CelevenRadixError}}{{{decoded_radix[1] - physical_radix[1]:+.4f} LSB}}",
        f"\\newcommand{{\\CtenRadixError}}{{{decoded_radix[2] - physical_radix[2]:+.4f} LSB}}",
        f"\\newcommand{{\\CalFinishTime}}{{{finish['time_s'] * 1e6:.3f} us}}",
        "\\newcommand{\\CalErrorFlag}{PASS}",
        f"\\newcommand{{\\MeasuredCtwelve}}{{{weights[0]:.4f}}}",
        f"\\newcommand{{\\MeasuredCeleven}}{{{weights[1]:.4f}}}",
        f"\\newcommand{{\\MeasuredCten}}{{{weights[2]:.4f}}}",
        f"\\newcommand{{\\MeasuredCnine}}{{{weights[3]:.4f}}}",
        f"\\newcommand{{\\MeasuredCR}}{{{weights[4]:.4f}}}",
        f"\\newcommand{{\\MeasuredCeight}}{{{weights[5]:.4f}}}",
    ]
    output = project / "reports" / "results_macros.tex"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(output)


if __name__ == "__main__":
    main()
