"""Generate LaTeX macros directly from frozen mismatch-matrix evidence."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


CASE_MACROS = {
    "ideal_zero_noise": "Ideal",
    "mismatch_0p5_zero_noise": "MZeroFiveZero",
    "mismatch_0p5_calnoise_0p3mV": "MZeroFiveNoise",
    "mismatch_1p0_zero_noise": "MOneZero",
    "mismatch_1p0_calnoise_0p3mV": "MOneNoise",
}


def _fmt(value: float, digits: int = 3) -> str:
    return f"{float(value):.{digits}f}"


def _macro(name: str, value: str | int) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


def generate(summary_path: Path, output_path: Path) -> None:
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    missing = summary.get("missing_cases", [])
    if missing:
        raise RuntimeError(f"cannot generate report metrics; missing {missing}")

    lines = [
        "% Generated by scripts/generate_report_metrics.py; do not edit.",
        _macro("MatrixPipelineHash", summary["provenance"]["pipeline_sha256"]),
        _macro(
            "MatrixCalibratorHash",
            summary["provenance"]["calibrator_sha256"],
        ),
        _macro(
            "MatrixConfigHash",
            summary["provenance"]["config_sha256"],
        ),
    ]
    for case_name, prefix in CASE_MACROS.items():
        case = summary["cases"][case_name]
        yield_data = case["yield"]
        transfer = case["transfer_integrity"]
        denominator = int(yield_data["denominator"])
        lines.extend(
            [
                _macro(f"{prefix}RunId", case["run_id"]),
                _macro(
                    f"{prefix}PreSndr",
                    _fmt(case["nominal_sndr_db"]["p50"]),
                ),
                _macro(
                    f"{prefix}CalSndr",
                    _fmt(case["calibrated_sndr_db"]["p50"]),
                ),
                _macro(
                    f"{prefix}CalSndrMin",
                    _fmt(case["calibrated_sndr_db"]["min"]),
                ),
                _macro(
                    f"{prefix}OracleSndr",
                    _fmt(case["physical_oracle_sndr_db"]["p50"]),
                ),
                _macro(
                    f"{prefix}CalEnob",
                    _fmt(case["calibrated_enob_bits"]["p50"]),
                ),
                _macro(
                    f"{prefix}CalEnobMin",
                    _fmt(case["calibrated_enob_bits"]["min"]),
                ),
                _macro(
                    f"{prefix}GapP",
                    _fmt(case["oracle_gap_db"]["p50"]),
                ),
                _macro(
                    f"{prefix}GapPNinetyFive",
                    _fmt(case["oracle_gap_db"]["p95"]),
                ),
                _macro(
                    f"{prefix}DynamicYield",
                    f"{yield_data['dynamic_pass']}/{denominator}",
                ),
                _macro(
                    f"{prefix}StaticYield",
                    f"{yield_data['code_density_pass']}/{denominator}",
                ),
                _macro(
                    f"{prefix}CombinedYield",
                    f"{yield_data['combined_pass']}/{denominator}",
                ),
                _macro(
                    f"{prefix}MissingCodes",
                    int(case["missing_codes_total"]),
                ),
                _macro(
                    f"{prefix}NegativeGainSeeds",
                    int(case["negative_gain_seed_count"]),
                ),
                _macro(
                    f"{prefix}Backsteps",
                    int(case["integer_backsteps_total"]),
                ),
                _macro(
                    f"{prefix}IntegerMonotonicSeeds",
                    int(transfer["integer_monotonic_seed_count"]),
                ),
                _macro(
                    f"{prefix}IntegerBackstepSeeds",
                    int(transfer["integer_backstep_seed_count"]),
                ),
                _macro(
                    f"{prefix}BackstepCountP",
                    _fmt(
                        transfer["integer_backsteps_per_seed"]["p50"],
                        1,
                    ),
                ),
                _macro(
                    f"{prefix}BackstepCountPNinetyFive",
                    _fmt(
                        transfer["integer_backsteps_per_seed"]["p95"],
                        1,
                    ),
                ),
                _macro(
                    f"{prefix}BackstepCountMax",
                    _fmt(
                        transfer["integer_backsteps_per_seed"]["max"],
                        0,
                    ),
                ),
                _macro(
                    f"{prefix}IntegerRollbackMax",
                    _fmt(transfer["max_integer_rollback_lsb"], 1),
                ),
                _macro(
                    f"{prefix}FloatRollbackMax",
                    _fmt(transfer["max_float_rollback_lsb"], 3),
                ),
                _macro(
                    f"{prefix}NonmonotonicFractionPPercent",
                    _fmt(
                        100.0
                        * transfer[
                            "integer_nonmonotonic_input_fraction"
                        ]["p50"],
                        4,
                    ),
                ),
                _macro(
                    f"{prefix}NonmonotonicFractionPNinetyFivePercent",
                    _fmt(
                        100.0
                        * transfer[
                            "integer_nonmonotonic_input_fraction"
                        ]["p95"],
                        4,
                    ),
                ),
                _macro(
                    f"{prefix}NonmonotonicFractionMaxPercent",
                    _fmt(
                        100.0
                        * transfer[
                            "integer_nonmonotonic_input_fraction"
                        ]["max"],
                        4,
                    ),
                ),
                _macro(
                    f"{prefix}DnlPeakMax",
                    _fmt(case["dnl_peak_lsb"]["max"], 4),
                ),
                _macro(
                    f"{prefix}InlPeakMax",
                    _fmt(case["inl_peak_lsb"]["max"], 4),
                ),
                _macro(
                    f"{prefix}FormalVerdict",
                    case["acceptance_verdict"],
                ),
            ]
        )

    for key, macro_prefix in (
        ("calibration_noise_effect_at_0p5pct", "NoiseEffectZeroFive"),
        ("calibration_noise_effect_at_1pct", "NoiseEffectOne"),
    ):
        effect = summary[key]
        lines.extend(
            [
                _macro(
                    f"{macro_prefix}SndrMedianDelta",
                    _fmt(effect["calibrated_sndr_p50_delta_db"]),
                ),
                _macro(
                    f"{macro_prefix}SndrMinDelta",
                    _fmt(effect["calibrated_sndr_min_delta_db"]),
                ),
                _macro(
                    f"{macro_prefix}GapPNinetyFiveDelta",
                    _fmt(effect["oracle_gap_p95_delta_db"]),
                ),
            ]
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    default_root = repo_root / "evidence" / "mismatch_matrix"
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--summary",
        type=Path,
        default=default_root / "mismatch_matrix_summary.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=repo_root / "docs" / "generated_metrics.tex",
    )
    args = parser.parse_args()
    generate(args.summary.resolve(), args.output.resolve())
    print(args.output.resolve())


if __name__ == "__main__":
    main()
